"""FunctorFlow v0: a lightweight categorical DSL for model design."""

from typing import TYPE_CHECKING

from .adapter_library import (
    ADAPTER_LIBRARIES,
    STANDARD_ADAPTER_LIBRARY,
    AdapterLibrary,
    AdapterSpec,
    get_adapter_library,
)
from .compiler import CompiledDiagram, ExecutionResult, compile_to_callable, compile_to_torch
from .core import (
    Adapter,
    Composition,
    Diagram,
    DiagramIR,
    IncludedDiagram,
    KanExtension,
    Morphism,
    Object,
    ObstructionLoss,
    Port,
)
from .macros import (
    BASKETWorkflowConfig,
    CompletionBlockConfig,
    DBSquareConfig,
    DemocritusGluingConfig,
    GTNeighborhoodConfig,
    KETBlockConfig,
    MACRO_LIBRARY,
    ROCKETRepairConfig,
    StructuredLMDualityConfig,
    BasketRocketPipelineConfig,
    basket_rocket_pipeline,
    basket_workflow_block,
    build_macro,
    completion_block,
    db_square,
    democritus_gluing_block,
    gt_neighborhood_block,
    ket_block,
    rocket_repair_block,
    structured_lm_duality,
)
from .proof_interface import (
    GENERATED_ROOT as PROOF_GENERATED_ROOT,
    PROOFS_ROOT,
    diagram_certificate_payload,
    render_lean_certificate,
    write_lean_certificate,
)
from .tutorial_library import (
    FOUNDATIONS_TUTORIAL_LIBRARY,
    PLANNING_TUTORIAL_LIBRARY,
    TUTORIAL_LIBRARIES,
    UNIFIED_TUTORIAL_LIBRARY,
    TutorialLibrary,
    get_tutorial_library,
    install_tutorial_library,
)

__all__ = [
    "ADAPTER_LIBRARIES",
    "STANDARD_ADAPTER_LIBRARY",
    "AdapterLibrary",
    "AdapterSpec",
    "FOUNDATIONS_TUTORIAL_LIBRARY",
    "PLANNING_TUTORIAL_LIBRARY",
    "CompiledDiagram",
    "Adapter",
    "Composition",
    "Diagram",
    "DiagramIR",
    "ExecutionResult",
    "IncludedDiagram",
    "KanExtension",
    "KETBlockConfig",
    "KETHeadConfig",
    "KETLanguageModelConfig",
    "KETStructuredLanguageModelConfig",
    "MACRO_LIBRARY",
    "Morphism",
    "Object",
    "ObstructionLoss",
    "Port",
    "PROOFS_ROOT",
    "PROOF_GENERATED_ROOT",
    "TUTORIAL_LIBRARIES",
    "TutorialLibrary",
    "UNIFIED_TUTORIAL_LIBRARY",
    "BASKETWorkflowConfig",
    "BasketRocketPipelineConfig",
    "DBSquareConfig",
    "CompletionBlockConfig",
    "DemocritusGluingConfig",
    "DemocritusArtifacts",
    "DemocritusCausalManifold",
    "DemocritusLLMConfig",
    "DemocritusPipelineConfig",
    "DemocritusQuestionRecord",
    "DemocritusStatementRecord",
    "DemocritusTopicNode",
    "DemocritusTriple",
    "GTNeighborhoodConfig",
    "OpenAICompatibleDemocritusClient",
    "ROCKETRepairConfig",
    "StructuredLMComparisonConfig",
    "StructuredLMDualityConfig",
    "basket_rocket_pipeline",
    "basket_workflow_block",
    "build_macro",
    "build_structured_language_model_diagram",
    "compare_structured_language_models",
    "completion_block",
    "compile_to_callable",
    "compile_to_torch",
    "db_square",
    "diagram_certificate_payload",
    "democritus_gluing_block",
    "build_democritus_pipeline_diagram",
    "extract_text_from_pdf",
    "get_adapter_library",
    "get_tutorial_library",
    "gt_neighborhood_block",
    "install_tutorial_library",
    "ket_block",
    "render_lean_certificate",
    "render_ket_demo_notebook",
    "render_ket_block_duality_notebook",
    "render_predict_detach_regime_notebook",
    "render_sudoku_demo_notebook",
    "render_ptb_model_comparison_notebook",
    "render_ptb_ket_language_model_notebook",
    "render_tutorial_library_notebook",
    "render_wiki2_model_comparison_notebook",
    "render_wiki2_ket_language_model_notebook",
    "rocket_repair_block",
    "run_democritus_pipeline_from_pdf",
    "run_democritus_pipelines_from_pdf_directory",
    "run_democritus_pipeline_from_text",
    "run_structured_language_model_experiment",
    "structured_lm_duality",
    "write_lean_certificate",
    "write_democritus_artifacts",
    "write_default_notebooks",
    "write_notebook",
]


if TYPE_CHECKING:
    from .democritus import (
        DemocritusArtifacts,
        DemocritusCausalManifold,
        DemocritusLLMConfig,
        DemocritusPipelineConfig,
        DemocritusQuestionRecord,
        DemocritusStatementRecord,
        DemocritusTopicNode,
        DemocritusTriple,
        OpenAICompatibleDemocritusClient,
        build_democritus_pipeline_diagram,
        extract_text_from_pdf,
        run_democritus_pipeline_from_pdf,
        run_democritus_pipelines_from_pdf_directory,
        run_democritus_pipeline_from_text,
        write_democritus_artifacts,
    )
    from .ket_lm import KETHeadConfig, KETLanguageModelConfig
    from .structured_lm import (
        KETStructuredLanguageModelConfig,
        StructuredLMComparisonConfig,
        build_structured_language_model_diagram,
        compare_structured_language_models,
        run_structured_language_model_experiment,
    )
    from .notebook_renderer import (
        render_ket_demo_notebook,
        render_ket_block_duality_notebook,
        render_predict_detach_regime_notebook,
        render_sudoku_demo_notebook,
        render_ptb_model_comparison_notebook,
        render_ptb_ket_language_model_notebook,
        render_tutorial_library_notebook,
        render_wiki2_model_comparison_notebook,
        render_wiki2_ket_language_model_notebook,
        write_default_notebooks,
        write_notebook,
    )


def __getattr__(name: str):
    if name in {
        "KETHeadConfig",
        "KETLanguageModelConfig",
        "DemocritusArtifacts",
        "DemocritusCausalManifold",
        "DemocritusLLMConfig",
        "DemocritusPipelineConfig",
        "DemocritusQuestionRecord",
        "DemocritusStatementRecord",
        "DemocritusTopicNode",
        "DemocritusTriple",
        "KETStructuredLanguageModelConfig",
        "OpenAICompatibleDemocritusClient",
        "StructuredLMComparisonConfig",
        "build_democritus_pipeline_diagram",
        "build_structured_language_model_diagram",
        "compare_structured_language_models",
        "extract_text_from_pdf",
        "run_democritus_pipeline_from_pdf",
        "run_democritus_pipelines_from_pdf_directory",
        "run_democritus_pipeline_from_text",
        "run_structured_language_model_experiment",
        "write_democritus_artifacts",
        "render_ket_demo_notebook",
        "render_ket_block_duality_notebook",
        "render_predict_detach_regime_notebook",
        "render_sudoku_demo_notebook",
        "render_ptb_model_comparison_notebook",
        "render_ptb_ket_language_model_notebook",
        "render_tutorial_library_notebook",
        "render_wiki2_model_comparison_notebook",
        "render_wiki2_ket_language_model_notebook",
        "write_default_notebooks",
        "write_notebook",
    }:
        if name in {"KETHeadConfig", "KETLanguageModelConfig"}:
            from .ket_lm import KETHeadConfig, KETLanguageModelConfig

            ket_exports = {
                "KETHeadConfig": KETHeadConfig,
                "KETLanguageModelConfig": KETLanguageModelConfig,
            }
            return ket_exports[name]
        if name in {
            "DemocritusArtifacts",
            "DemocritusCausalManifold",
            "DemocritusLLMConfig",
            "DemocritusPipelineConfig",
            "DemocritusQuestionRecord",
            "DemocritusStatementRecord",
            "DemocritusTopicNode",
            "DemocritusTriple",
            "OpenAICompatibleDemocritusClient",
            "build_democritus_pipeline_diagram",
            "extract_text_from_pdf",
            "run_democritus_pipeline_from_pdf",
            "run_democritus_pipelines_from_pdf_directory",
            "run_democritus_pipeline_from_text",
            "write_democritus_artifacts",
        }:
            from .democritus import (
                DemocritusArtifacts,
                DemocritusCausalManifold,
                DemocritusLLMConfig,
                DemocritusPipelineConfig,
                DemocritusQuestionRecord,
                DemocritusStatementRecord,
                DemocritusTopicNode,
                DemocritusTriple,
                OpenAICompatibleDemocritusClient,
                build_democritus_pipeline_diagram,
                extract_text_from_pdf,
                run_democritus_pipeline_from_pdf,
                run_democritus_pipelines_from_pdf_directory,
                run_democritus_pipeline_from_text,
                write_democritus_artifacts,
            )

            democritus_exports = {
                "DemocritusArtifacts": DemocritusArtifacts,
                "DemocritusCausalManifold": DemocritusCausalManifold,
                "DemocritusLLMConfig": DemocritusLLMConfig,
                "DemocritusPipelineConfig": DemocritusPipelineConfig,
                "DemocritusQuestionRecord": DemocritusQuestionRecord,
                "DemocritusStatementRecord": DemocritusStatementRecord,
                "DemocritusTopicNode": DemocritusTopicNode,
                "DemocritusTriple": DemocritusTriple,
                "OpenAICompatibleDemocritusClient": OpenAICompatibleDemocritusClient,
                "build_democritus_pipeline_diagram": build_democritus_pipeline_diagram,
                "extract_text_from_pdf": extract_text_from_pdf,
                "run_democritus_pipeline_from_pdf": run_democritus_pipeline_from_pdf,
                "run_democritus_pipelines_from_pdf_directory": run_democritus_pipelines_from_pdf_directory,
                "run_democritus_pipeline_from_text": run_democritus_pipeline_from_text,
                "write_democritus_artifacts": write_democritus_artifacts,
            }
            return democritus_exports[name]
        if name in {
            "KETStructuredLanguageModelConfig",
            "StructuredLMComparisonConfig",
            "build_structured_language_model_diagram",
            "compare_structured_language_models",
            "run_structured_language_model_experiment",
        }:
            from .structured_lm import (
                KETStructuredLanguageModelConfig,
                StructuredLMComparisonConfig,
                build_structured_language_model_diagram,
                compare_structured_language_models,
                run_structured_language_model_experiment,
            )

            structured_lm_exports = {
                "KETStructuredLanguageModelConfig": KETStructuredLanguageModelConfig,
                "StructuredLMComparisonConfig": StructuredLMComparisonConfig,
                "build_structured_language_model_diagram": build_structured_language_model_diagram,
                "compare_structured_language_models": compare_structured_language_models,
                "run_structured_language_model_experiment": run_structured_language_model_experiment,
            }
            return structured_lm_exports[name]
        from .notebook_renderer import (
            render_ket_demo_notebook,
            render_ket_block_duality_notebook,
            render_predict_detach_regime_notebook,
            render_sudoku_demo_notebook,
            render_ptb_model_comparison_notebook,
            render_ptb_ket_language_model_notebook,
            render_tutorial_library_notebook,
            render_wiki2_model_comparison_notebook,
            render_wiki2_ket_language_model_notebook,
            write_default_notebooks,
            write_notebook,
        )

        exports = {
            "render_ket_demo_notebook": render_ket_demo_notebook,
            "render_ket_block_duality_notebook": render_ket_block_duality_notebook,
            "render_predict_detach_regime_notebook": render_predict_detach_regime_notebook,
            "render_sudoku_demo_notebook": render_sudoku_demo_notebook,
            "render_ptb_model_comparison_notebook": render_ptb_model_comparison_notebook,
            "render_ptb_ket_language_model_notebook": render_ptb_ket_language_model_notebook,
            "render_tutorial_library_notebook": render_tutorial_library_notebook,
            "render_wiki2_model_comparison_notebook": render_wiki2_model_comparison_notebook,
            "render_wiki2_ket_language_model_notebook": render_wiki2_ket_language_model_notebook,
            "write_default_notebooks": write_default_notebooks,
            "write_notebook": write_notebook,
        }
        return exports[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
